### ISSUE TITLE
make build doesn't work

### ISSUE THREAD

**Issue by jiixing** [dliggat/local-lambda-toolkit#2]
I got empty string in the $@DEPLOY_DIRS . 
Output of make build:
> cp *.py package
> cp *.yaml package
> cp -R  package
> cp: missing destination file operand after 'package'

Tested under ubuntu and debian linux

**Comment by dliggat** [comment]
Thanks for the info. Works in macOS 10.12 - must be a difference in `cp` behaviour. Will fix.

**Comment by dliggat** [comment]
Fixed by #3
